# Generated by Django 5.1.1 on 2024-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
