# Generated by Django 5.1.1 on 2024-10-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
